-- ============================================================
-- P1-4 五官（眼/听力/口腔）病历模板 SQL 初始化数据
-- 需求 18 / 22 / 26 ▲：12 套眼/听力/口腔保健病历模板
-- 同时附带 12 套体格检查病历模板（需求 13）
-- 共 4 类 × 12 套 = 48 套模板
--
-- 约定：
--   template_type 取值与 MedicalRecordTemplateDO 注释、
--   ChildHealthWorkflowServiceImpl 使用的常量一致：
--     GENERAL_CHECKUP / EYE_HEALTH / HEARING_HEALTH / ORAL_HEALTH
--   status：1=启用（TINYINT，与表 DDL 一致）
--   template_content：结构化字段 schema + defaultValuesJson
--     （供 P1 阶段后续"一键填充"消费）
--   field_mapping：VO 字段 → DO 字段映射（供结构化填充使用）
--   abnormality_thresholds：基础异常阈值（与 AbnormalRuleService 配合）
-- 使用 INSERT IGNORE 保证幂等，可重复执行。
-- ============================================================

START TRANSACTION;

-- 1. 眼保健病历模板（需求18 ▲，12 套）
INSERT IGNORE INTO `medical_record_template`
  (`template_code`, `template_name`, `template_type`, `age_month_min`, `age_month_max`,
   `norm_version`, `description`, `template_content`, `field_mapping`,
   `abnormality_thresholds`, `health_guidance`, `follow_up_recommendation`,
   `sort_order`, `status`)
VALUES
  ('EYE-01M', '满月眼保健病历模板', 'EYE_HEALTH', 0, 1,
   '《0-6岁儿童眼保健及视力检查服务规范（2021年版）》', '新生儿满月眼保健检查标准模板',
   '{"schemaVersion":1,"items":["eyelid","conjunctiva","cornea","pupil","eyePosition","eyeAppearance","redReflexTest","pupilLightReflex"],"defaultValues":{"redReflexTest":"正常","pupilLightReflex":"存在","eyePosition":"正位"}}',
   '{"eyelid":"normal|abnormal","redReflexTest":"正常|异常","pupilLightReflex":"存在|缺失|不对称"}',
   '{"riskFactors":["早产","低出生体重","家族史"],"abnormalThreshold":{"redReflexTest":"异常","pupilLightReflex":"缺失|不对称"}}',
   '{"guidance":"注意光线刺激、避免强光直射，发现异常及时转诊眼科"}',
   '{"recommendation":"下次眼保健检查时间：3月龄","followupType":"EYE_HEALTH"}',
   1, 1),
  ('EYE-03M', '3月龄眼保健病历模板', 'EYE_HEALTH', 2, 4,
   '《0-6岁儿童眼保健及视力检查服务规范（2021年版）》', '婴儿3月龄眼保健检查标准模板',
   '{"schemaVersion":1,"items":["eyelid","conjunctiva","cornea","pupil","eyePosition","eyeAppearance","redReflexTest","pupilLightReflex"],"defaultValues":{"redReflexTest":"正常","pupilLightReflex":"存在","eyePosition":"正位"}}',
   '{"eyelid":"normal|abnormal","redReflexTest":"正常|异常"}',
   '{"abnormalThreshold":{"redReflexTest":"异常","pupilLightReflex":"缺失|不对称"}}',
   '{"guidance":"可追视移动目标，注意观察注视方向"}',
   '{"recommendation":"下次眼保健检查时间：6月龄","followupType":"EYE_HEALTH"}',
   2, 1),
  ('EYE-06M', '6月龄眼保健病历模板', 'EYE_HEALTH', 5, 7,
   '《0-6岁儿童眼保健及视力检查服务规范（2021年版）》', '婴儿6月龄眼保健检查标准模板',
   '{"schemaVersion":1,"items":["eyelid","conjunctiva","cornea","pupil","leftVision","rightVision","leftDiopter","rightDiopter","eyePosition","eyeAppearance","redReflexTest","pupilLightReflex"],"defaultValues":{"redReflexTest":"正常","pupilLightReflex":"存在","eyePosition":"正位"}}',
   '{"leftDiopter":"number","rightDiopter":"number","eyePosition":"正位|斜视"}',
   '{"abnormalThreshold":{"leftDiopter":">+3.00D|<-1.00D","rightDiopter":">+3.00D|<-1.00D","eyePosition":"斜视"}}',
   '{"guidance":"开始视觉发育关键期，注意追视、注视能力训练"}',
   '{"recommendation":"下次眼保健检查时间：8月龄","followupType":"EYE_HEALTH"}',
   3, 1),
  ('EYE-08M', '8月龄眼保健病历模板', 'EYE_HEALTH', 8, 10,
   '《0-6岁儿童眼保健及视力检查服务规范（2021年版）》', '婴儿8月龄眼保健检查标准模板',
   '{"schemaVersion":1,"items":["eyelid","conjunctiva","cornea","pupil","eyePosition","eyeAppearance","redReflexTest","pupilLightReflex"],"defaultValues":{"redReflexTest":"正常","pupilLightReflex":"存在","eyePosition":"正位"}}',
   '{"redReflexTest":"正常|异常","eyePosition":"正位|斜视"}',
   '{"abnormalThreshold":{"redReflexTest":"异常","eyePosition":"斜视"}}',
   '{"guidance":"可固视物体，注意观察眼球运动"}',
   '{"recommendation":"下次眼保健检查时间：12月龄","followupType":"EYE_HEALTH"}',
   4, 1),
  ('EYE-12M', '12月龄眼保健病历模板', 'EYE_HEALTH', 11, 14,
   '《0-6岁儿童眼保健及视力检查服务规范（2021年版）》', '婴儿12月龄眼保健检查标准模板',
   '{"schemaVersion":1,"items":["eyelid","conjunctiva","cornea","pupil","leftVision","rightVision","leftDiopter","rightDiopter","eyePosition","strabismus","eyeAppearance","redReflexTest","pupilLightReflex"],"defaultValues":{"redReflexTest":"正常","pupilLightReflex":"存在","eyePosition":"正位","strabismus":"无"}}',
   '{"leftDiopter":"number","rightDiopter":"number","strabismus":"无|有"}',
   '{"abnormalThreshold":{"leftDiopter":">+3.00D","rightDiopter":">+3.00D","strabismus":"有"}}',
   '{"guidance":"1岁是斜视、屈光不正筛查的关键期，发现异常及时散瞳验光"}',
   '{"recommendation":"下次眼保健检查时间：18月龄","followupType":"EYE_HEALTH"}',
   5, 1),
  ('EYE-18M', '18月龄眼保健病历模板', 'EYE_HEALTH', 15, 20,
   '《0-6岁儿童眼保健及视力检查服务规范（2021年版）》', '幼儿18月龄眼保健检查标准模板',
   '{"schemaVersion":1,"items":["eyelid","conjunctiva","cornea","pupil","leftVision","rightVision","leftDiopter","rightDiopter","eyePosition","strabismus","eyeAppearance","fundusExam"],"defaultValues":{"eyePosition":"正位","strabismus":"无"}}',
   '{"leftDiopter":"number","rightDiopter":"number","strabismus":"无|有"}',
   '{"abnormalThreshold":{"leftDiopter":">+3.00D|<-1.00D","rightDiopter":">+3.00D|<-1.00D","strabismus":"有"}}',
   '{"guidance":"可识别图形视力表，建议定期复查屈光度"}',
   '{"recommendation":"下次眼保健检查时间：24月龄","followupType":"EYE_HEALTH"}',
   6, 1),
  ('EYE-24M', '24月龄眼保健病历模板', 'EYE_HEALTH', 21, 26,
   '《0-6岁儿童眼保健及视力检查服务规范（2021年版）》', '幼儿24月龄眼保健检查标准模板',
   '{"schemaVersion":1,"items":["eyelid","conjunctiva","cornea","pupil","leftVision","rightVision","leftDiopter","rightDiopter","eyePosition","strabismus","eyeAppearance","fundusExam"],"defaultValues":{"leftVision":"0.5+","rightVision":"0.5+","eyePosition":"正位","strabismus":"无"}}',
   '{"leftVision":"number","rightVision":"number","leftDiopter":"number","rightDiopter":"number"}',
   '{"abnormalThreshold":{"leftVision":"<0.5","rightVision":"<0.5","leftDiopter":">+3.00D|<-1.00D","rightDiopter":">+3.00D|<-1.00D","strabismus":"有"}}',
   '{"guidance":"2岁起可开始图形视力表检查，关注远视储备"}',
   '{"recommendation":"下次眼保健检查时间：30月龄","followupType":"EYE_HEALTH"}',
   7, 1),
  ('EYE-30M', '30月龄眼保健病历模板', 'EYE_HEALTH', 27, 35,
   '《0-6岁儿童眼保健及视力检查服务规范（2021年版）》', '幼儿30月龄眼保健检查标准模板',
   '{"schemaVersion":1,"items":["eyelid","conjunctiva","cornea","pupil","leftVision","rightVision","leftDiopter","rightDiopter","eyePosition","strabismus","eyeAppearance","fundusExam"],"defaultValues":{"leftVision":"0.6+","rightVision":"0.6+","eyePosition":"正位","strabismus":"无"}}',
   '{"leftVision":"number","rightVision":"number","leftDiopter":"number","rightDiopter":"number"}',
   '{"abnormalThreshold":{"leftVision":"<0.6","rightVision":"<0.6","strabismus":"有"}}',
   '{"guidance":"定期监测屈光度，预防近视发生"}',
   '{"recommendation":"下次眼保健检查时间：3岁","followupType":"EYE_HEALTH"}',
   8, 1),
  ('EYE-3Y', '3岁眼保健病历模板', 'EYE_HEALTH', 36, 42,
   '《0-6岁儿童眼保健及视力检查服务规范（2021年版）》', '学龄前儿童3岁眼保健检查标准模板',
   '{"schemaVersion":1,"items":["eyelid","conjunctiva","cornea","pupil","leftVision","rightVision","leftDiopter","rightDiopter","eyePosition","strabismus","eyeAppearance","fundusExam"],"defaultValues":{"leftVision":"0.7+","rightVision":"0.7+","eyePosition":"正位","strabismus":"无"}}',
   '{"leftVision":"number","rightVision":"number","leftDiopter":"number","rightDiopter":"number"}',
   '{"abnormalThreshold":{"leftVision":"<0.7","rightVision":"<0.7","leftDiopter":">+3.00D|<-1.00D","rightDiopter":">+3.00D|<-1.00D","strabismus":"有"}}',
   '{"guidance":"3岁起可使用国际标准视力表，建立视力档案"}',
   '{"recommendation":"下次眼保健检查时间：4岁","followupType":"EYE_HEALTH"}',
   9, 1),
  ('EYE-4Y', '4岁眼保健病历模板', 'EYE_HEALTH', 43, 54,
   '《0-6岁儿童眼保健及视力检查服务规范（2021年版）》', '学龄前儿童4岁眼保健检查标准模板',
   '{"schemaVersion":1,"items":["eyelid","conjunctiva","cornea","pupil","leftVision","rightVision","leftDiopter","rightDiopter","eyePosition","strabismus","eyeAppearance","fundusExam"],"defaultValues":{"leftVision":"0.8+","rightVision":"0.8+","eyePosition":"正位","strabismus":"无"}}',
   '{"leftVision":"number","rightVision":"number","leftDiopter":"number","rightDiopter":"number"}',
   '{"abnormalThreshold":{"leftVision":"<0.8","rightVision":"<0.8","strabismus":"有"}}',
   '{"guidance":"每年至少 1 次视力检查，注意用眼卫生"}',
   '{"recommendation":"下次眼保健检查时间：5岁","followupType":"EYE_HEALTH"}',
   10, 1),
  ('EYE-5Y', '5岁眼保健病历模板', 'EYE_HEALTH', 55, 66,
   '《0-6岁儿童眼保健及视力检查服务规范（2021年版）》', '学龄前儿童5岁眼保健检查标准模板',
   '{"schemaVersion":1,"items":["eyelid","conjunctiva","cornea","pupil","leftVision","rightVision","leftDiopter","rightDiopter","eyePosition","strabismus","eyeAppearance","fundusExam"],"defaultValues":{"leftVision":"0.9+","rightVision":"0.9+","eyePosition":"正位","strabismus":"无"}}',
   '{"leftVision":"number","rightVision":"number","leftDiopter":"number","rightDiopter":"number"}',
   '{"abnormalThreshold":{"leftVision":"<0.9","rightVision":"<0.9","strabismus":"有"}}',
   '{"guidance":"学龄前期是近视防控关键期，控制电子屏幕使用时间"}',
   '{"recommendation":"下次眼保健检查时间：6岁","followupType":"EYE_HEALTH"}',
   11, 1),
  ('EYE-6Y', '6岁眼保健病历模板', 'EYE_HEALTH', 67, 78,
   '《0-6岁儿童眼保健及视力检查服务规范（2021年版）》', '学龄儿童6岁眼保健检查标准模板',
   '{"schemaVersion":1,"items":["eyelid","conjunctiva","cornea","pupil","leftVision","rightVision","leftDiopter","rightDiopter","eyePosition","strabismus","eyeAppearance","fundusExam"],"defaultValues":{"leftVision":"1.0+","rightVision":"1.0+","eyePosition":"正位","strabismus":"无"}}',
   '{"leftVision":"number","rightVision":"number","leftDiopter":"number","rightDiopter":"number"}',
   '{"abnormalThreshold":{"leftVision":"<1.0","rightVision":"<1.0","strabismus":"有"}}',
   '{"guidance":"入学前完成全面眼科检查，建立长期视力档案"}',
   '{"recommendation":"建议每年至少 1 次视力检查","followupType":"EYE_HEALTH"}',
   12, 1);

-- 2. 听力保健病历模板（需求22 ▲，12 套）
INSERT IGNORE INTO `medical_record_template`
  (`template_code`, `template_name`, `template_type`, `age_month_min`, `age_month_max`,
   `norm_version`, `description`, `template_content`, `field_mapping`,
   `abnormality_thresholds`, `health_guidance`, `follow_up_recommendation`,
   `sort_order`, `status`)
VALUES
  ('HEARING-01M', '满月听力保健病历模板', 'HEARING_HEALTH', 0, 1,
   '《儿童耳及听力保健技术规范》', '新生儿满月听力保健检查标准模板',
   '{"schemaVersion":1,"items":["auricleLeft","auricleRight","earCanalLeft","earCanalRight","tympanicLeft","tympanicRight","screeningMethod","screeningLeft","screeningRight","hearingScreening","earAppearance","externalAuditory","tympanicMembrane"],"defaultValues":{"screeningMethod":"OAE","screeningLeft":"PASS","screeningRight":"PASS","hearingScreening":"通过"}}',
   '{"screeningMethod":"OAE|AABR","screeningLeft":"PASS|REFER","screeningRight":"PASS|REFER","hearingScreening":"通过|未通过"}',
   '{"abnormalThreshold":{"screeningLeft":"REFER","screeningRight":"REFER","hearingScreening":"未通过"}}',
   '{"guidance":"满月进行首次听力筛查，未通过者 42 天内复筛"}',
   '{"recommendation":"复筛未通过者 3 月龄内转诊听力中心","followupType":"HEARING_HEALTH"}',
   1, 1),
  ('HEARING-03M', '3月龄听力保健病历模板', 'HEARING_HEALTH', 2, 4,
   '《儿童耳及听力保健技术规范》', '婴儿3月龄听力保健检查标准模板',
   '{"schemaVersion":1,"items":["auricleLeft","auricleRight","earCanalLeft","earCanalRight","tympanicLeft","tympanicRight","screeningMethod","screeningLeft","screeningRight","hearingScreening","earAppearance","externalAuditory","tympanicMembrane"],"defaultValues":{"screeningMethod":"AABR","screeningLeft":"PASS","screeningRight":"PASS","hearingScreening":"通过"}}',
   '{"screeningMethod":"OAE|AABR","screeningLeft":"PASS|REFER","screeningRight":"PASS|REFER"}',
   '{"abnormalThreshold":{"screeningLeft":"REFER","screeningRight":"REFER","hearingScreening":"未通过"}}',
   '{"guidance":"3 月龄为复筛关键期，AABR 是金标准"}',
   '{"recommendation":"复筛未通过者转诊听力确诊","followupType":"HEARING_HEALTH"}',
   2, 1),
  ('HEARING-06M', '6月龄听力保健病历模板', 'HEARING_HEALTH', 5, 7,
   '《儿童耳及听力保健技术规范》', '婴儿6月龄听力保健检查标准模板',
   '{"schemaVersion":1,"items":["auricleLeft","auricleRight","earCanalLeft","earCanalRight","tympanicLeft","tympanicRight","screeningMethod","screeningLeft","screeningRight","leftEarResult","rightEarResult","hearingScreening","earAppearance","externalAuditory","tympanicMembrane"],"defaultValues":{"screeningMethod":"OAE","screeningLeft":"PASS","screeningRight":"PASS","hearingScreening":"通过"}}',
   '{"screeningMethod":"OAE|AABR|VisualResponse","screeningLeft":"PASS|REFER","screeningRight":"PASS|REFER"}',
   '{"abnormalThreshold":{"screeningLeft":"REFER","screeningRight":"REFER","hearingScreening":"未通过"}}',
   '{"guidance":"可使用视觉强化测听，关注行为反应"}',
   '{"recommendation":"每年 1 次听力筛查","followupType":"HEARING_HEALTH"}',
   3, 1),
  ('HEARING-08M', '8月龄听力保健病历模板', 'HEARING_HEALTH', 8, 10,
   '《儿童耳及听力保健技术规范》', '婴儿8月龄听力保健检查标准模板',
   '{"schemaVersion":1,"items":["auricleLeft","auricleRight","earCanalLeft","earCanalRight","tympanicLeft","tympanicRight","screeningMethod","screeningLeft","screeningRight","leftEarResult","rightEarResult","hearingScreening","earAppearance","externalAuditory","tympanicMembrane"],"defaultValues":{"screeningMethod":"OAE","screeningLeft":"PASS","screeningRight":"PASS","hearingScreening":"通过"}}',
   '{"screeningMethod":"OAE|AABR","screeningLeft":"PASS|REFER","screeningRight":"PASS|REFER"}',
   '{"abnormalThreshold":{"hearingScreening":"未通过"}}',
   '{"guidance":"关注对声音的反应（如转头、眨眼）"}',
   '{"recommendation":"如有异常转诊听力中心","followupType":"HEARING_HEALTH"}',
   4, 1),
  ('HEARING-12M', '12月龄听力保健病历模板', 'HEARING_HEALTH', 11, 14,
   '《儿童耳及听力保健技术规范》', '婴儿12月龄听力保健检查标准模板',
   '{"schemaVersion":1,"items":["auricleLeft","auricleRight","earCanalLeft","earCanalRight","tympanicLeft","tympanicRight","screeningMethod","screeningLeft","screeningRight","leftEarResult","rightEarResult","hearingScreening","earAppearance","externalAuditory","tympanicMembrane"],"defaultValues":{"screeningMethod":"VRA","screeningLeft":"PASS","screeningRight":"PASS","hearingScreening":"通过"}}',
   '{"screeningMethod":"OAE|VRA","screeningLeft":"PASS|REFER","screeningRight":"PASS|REFER"}',
   '{"abnormalThreshold":{"hearingScreening":"未通过"}}',
   '{"guidance":"开始语言发育关键期，注意对名字呼喊的反应"}',
   '{"recommendation":"每年 1 次听力筛查","followupType":"HEARING_HEALTH"}',
   5, 1),
  ('HEARING-18M', '18月龄听力保健病历模板', 'HEARING_HEALTH', 15, 20,
   '《儿童耳及听力保健技术规范》', '幼儿18月龄听力保健检查标准模板',
   '{"schemaVersion":1,"items":["auricleLeft","auricleRight","earCanalLeft","earCanalRight","tympanicLeft","tympanicRight","screeningMethod","screeningLeft","screeningRight","leftEarResult","rightEarResult","hearingScreening","earAppearance","externalAuditory","tympanicMembrane"],"defaultValues":{"screeningMethod":"VRA","screeningLeft":"PASS","screeningRight":"PASS","hearingScreening":"通过"}}',
   '{"screeningMethod":"VRA|PA","screeningLeft":"PASS|REFER","screeningRight":"PASS|REFER"}',
   '{"abnormalThreshold":{"hearingScreening":"未通过"}}',
   '{"guidance":"语言发育迟缓者须排查听力问题"}',
   '{"recommendation":"如有语言发育迟缓或听力异常转诊","followupType":"HEARING_HEALTH"}',
   6, 1),
  ('HEARING-24M', '24月龄听力保健病历模板', 'HEARING_HEALTH', 21, 26,
   '《儿童耳及听力保健技术规范》', '幼儿24月龄听力保健检查标准模板',
   '{"schemaVersion":1,"items":["auricleLeft","auricleRight","earCanalLeft","earCanalRight","tympanicLeft","tympanicRight","screeningMethod","screeningLeft","screeningRight","leftEarResult","rightEarResult","hearingScreening","earAppearance","externalAuditory","tympanicMembrane"],"defaultValues":{"screeningMethod":"PA","screeningLeft":"PASS","screeningRight":"PASS","hearingScreening":"通过"}}',
   '{"screeningMethod":"PA|VRA","screeningLeft":"PASS|REFER","screeningRight":"PASS|REFER"}',
   '{"abnormalThreshold":{"hearingScreening":"未通过"}}',
   '{"guidance":"可配合游戏测听，关注语言表达清晰度"}',
   '{"recommendation":"每年 1 次听力筛查","followupType":"HEARING_HEALTH"}',
   7, 1),
  ('HEARING-30M', '30月龄听力保健病历模板', 'HEARING_HEALTH', 27, 35,
   '《儿童耳及听力保健技术规范》', '幼儿30月龄听力保健检查标准模板',
   '{"schemaVersion":1,"items":["auricleLeft","auricleRight","earCanalLeft","earCanalRight","tympanicLeft","tympanicRight","screeningMethod","screeningLeft","screeningRight","leftEarResult","rightEarResult","hearingScreening","earAppearance","externalAuditory","tympanicMembrane"],"defaultValues":{"screeningMethod":"PA","screeningLeft":"PASS","screeningRight":"PASS","hearingScreening":"通过"}}',
   '{"screeningMethod":"PA|Tympanometry","screeningLeft":"PASS|REFER","screeningRight":"PASS|REFER"}',
   '{"abnormalThreshold":{"hearingScreening":"未通过","tympanicMembrane":"异常"}}',
   '{"guidance":"上呼吸道感染后须复查听力，预防分泌性中耳炎"}',
   '{"recommendation":"如有异常转诊","followupType":"HEARING_HEALTH"}',
   8, 1),
  ('HEARING-3Y', '3岁听力保健病历模板', 'HEARING_HEALTH', 36, 42,
   '《儿童耳及听力保健技术规范》', '学龄前儿童3岁听力保健检查标准模板',
   '{"schemaVersion":1,"items":["auricleLeft","auricleRight","earCanalLeft","earCanalRight","tympanicLeft","tympanicRight","screeningMethod","screeningLeft","screeningRight","leftEarResult","rightEarResult","hearingScreening","earAppearance","externalAuditory","tympanicMembrane"],"defaultValues":{"screeningMethod":"PA","screeningLeft":"PASS","screeningRight":"PASS","hearingScreening":"通过"}}',
   '{"screeningMethod":"PA|PureTone","screeningLeft":"PASS|REFER","screeningRight":"PASS|REFER"}',
   '{"abnormalThreshold":{"hearingScreening":"未通过","leftEarResult":"异常","rightEarResult":"异常"}}',
   '{"guidance":"3 岁起可配合纯音测听，入园前完成听力筛查"}',
   '{"recommendation":"每年 1 次听力筛查","followupType":"HEARING_HEALTH"}',
   9, 1),
  ('HEARING-4Y', '4岁听力保健病历模板', 'HEARING_HEALTH', 43, 54,
   '《儿童耳及听力保健技术规范》', '学龄前儿童4岁听力保健检查标准模板',
   '{"schemaVersion":1,"items":["auricleLeft","auricleRight","earCanalLeft","earCanalRight","tympanicLeft","tympanicRight","screeningMethod","screeningLeft","screeningRight","leftEarResult","rightEarResult","hearingScreening","earAppearance","externalAuditory","tympanicMembrane"],"defaultValues":{"screeningMethod":"PureTone","screeningLeft":"PASS","screeningRight":"PASS","hearingScreening":"通过"}}',
   '{"screeningMethod":"PureTone","screeningLeft":"PASS|REFER","screeningRight":"PASS|REFER"}',
   '{"abnormalThreshold":{"hearingScreening":"未通过"}}',
   '{"guidance":"入园前完成听力筛查，注意反复上呼吸道感染的影响"}',
   '{"recommendation":"每年 1 次听力筛查","followupType":"HEARING_HEALTH"}',
   10, 1),
  ('HEARING-5Y', '5岁听力保健病历模板', 'HEARING_HEALTH', 55, 66,
   '《儿童耳及听力保健技术规范》', '学龄前儿童5岁听力保健检查标准模板',
   '{"schemaVersion":1,"items":["auricleLeft","auricleRight","earCanalLeft","earCanalRight","tympanicLeft","tympanicRight","screeningMethod","screeningLeft","screeningRight","leftEarResult","rightEarResult","hearingScreening","earAppearance","externalAuditory","tympanicMembrane"],"defaultValues":{"screeningMethod":"PureTone","screeningLeft":"PASS","screeningRight":"PASS","hearingScreening":"通过"}}',
   '{"screeningMethod":"PureTone","screeningLeft":"PASS|REFER","screeningRight":"PASS|REFER"}',
   '{"abnormalThreshold":{"hearingScreening":"未通过"}}',
   '{"guidance":"学龄前完成全面听力评估"}',
   '{"recommendation":"每年 1 次听力筛查","followupType":"HEARING_HEALTH"}',
   11, 1),
  ('HEARING-6Y', '6岁听力保健病历模板', 'HEARING_HEALTH', 67, 78,
   '《儿童耳及听力保健技术规范》', '学龄儿童6岁听力保健检查标准模板',
   '{"schemaVersion":1,"items":["auricleLeft","auricleRight","earCanalLeft","earCanalRight","tympanicLeft","tympanicRight","screeningMethod","screeningLeft","screeningRight","leftEarResult","rightEarResult","hearingScreening","earAppearance","externalAuditory","tympanicMembrane"],"defaultValues":{"screeningMethod":"PureTone","screeningLeft":"PASS","screeningRight":"PASS","hearingScreening":"通过"}}',
   '{"screeningMethod":"PureTone","screeningLeft":"PASS|REFER","screeningRight":"PASS|REFER"}',
   '{"abnormalThreshold":{"hearingScreening":"未通过"}}',
   '{"guidance":"入学前完成听力筛查，注意耳机使用安全"}',
   '{"recommendation":"建议每年 1 次听力检查","followupType":"HEARING_HEALTH"}',
   12, 1);

-- 3. 口腔保健病历模板（需求26 ▲，12 套）
INSERT IGNORE INTO `medical_record_template`
  (`template_code`, `template_name`, `template_type`, `age_month_min`, `age_month_max`,
   `norm_version`, `description`, `template_content`, `field_mapping`,
   `abnormality_thresholds`, `health_guidance`, `follow_up_recommendation`,
   `sort_order`, `status`)
VALUES
  ('ORAL-01M', '满月口腔保健病历模板', 'ORAL_HEALTH', 0, 1,
   '《儿童口腔保健指导技术规范》', '新生儿满月口腔保健检查标准模板',
   '{"schemaVersion":1,"items":["toothCount","cariesCount","missingTooth","filledTooth","dmftIndex","cariesType","gumCondition","oralMucosa","tongue","palate","occlusion","oralHygiene","malocclusion"],"defaultValues":{"toothCount":0,"cariesCount":0,"missingTooth":0,"filledTooth":0,"dmftIndex":0,"gumCondition":"正常","oralMucosa":"正常","tongue":"正常","palate":"正常","oralHygiene":"良好"}}',
   '{"toothCount":"number","cariesCount":"number","dmftIndex":"number"}',
   '{"abnormalThreshold":{"cariesCount":">0","gumCondition":"异常","oralMucosa":"异常","tongue":"异常","palate":"异常"}}',
   '{"guidance":"注意口腔清洁，喂奶后擦拭口腔，避免奶瓶龋"}',
   '{"recommendation":"下次口腔保健检查时间：3月龄","followupType":"ORAL_HEALTH"}',
   1, 1),
  ('ORAL-03M', '3月龄口腔保健病历模板', 'ORAL_HEALTH', 2, 4,
   '《儿童口腔保健指导技术规范》', '婴儿3月龄口腔保健检查标准模板',
   '{"schemaVersion":1,"items":["toothCount","cariesCount","missingTooth","filledTooth","dmftIndex","cariesType","gumCondition","oralMucosa","tongue","palate","occlusion","oralHygiene","malocclusion"],"defaultValues":{"toothCount":0,"cariesCount":0,"gumCondition":"正常","oralHygiene":"良好"}}',
   '{"toothCount":"number","cariesCount":"number","dmftIndex":"number"}',
   '{"abnormalThreshold":{"cariesCount":">0","gumCondition":"异常"}}',
   '{"guidance":"关注乳牙萌出情况，开始口腔清洁习惯培养"}',
   '{"recommendation":"下次口腔保健检查时间：6月龄","followupType":"ORAL_HEALTH"}',
   2, 1),
  ('ORAL-06M', '6月龄口腔保健病历模板', 'ORAL_HEALTH', 5, 7,
   '《儿童口腔保健指导技术规范》', '婴儿6月龄口腔保健检查标准模板',
   '{"schemaVersion":1,"items":["toothCount","cariesCount","missingTooth","filledTooth","dmftIndex","cariesType","gumCondition","oralMucosa","tongue","palate","occlusion","oralHygiene","malocclusion"],"defaultValues":{"toothCount":2,"cariesCount":0,"gumCondition":"正常","oralHygiene":"良好"}}',
   '{"toothCount":"number","cariesCount":"number","dmftIndex":"number"}',
   '{"abnormalThreshold":{"cariesCount":">0","oralHygiene":"差"}}',
   '{"guidance":"乳牙开始萌出，使用指套牙刷清洁"}',
   '{"recommendation":"下次口腔保健检查时间：8月龄","followupType":"ORAL_HEALTH"}',
   3, 1),
  ('ORAL-08M', '8月龄口腔保健病历模板', 'ORAL_HEALTH', 8, 10,
   '《儿童口腔保健指导技术规范》', '婴儿8月龄口腔保健检查标准模板',
   '{"schemaVersion":1,"items":["toothCount","cariesCount","missingTooth","filledTooth","dmftIndex","cariesType","gumCondition","oralMucosa","tongue","palate","occlusion","oralHygiene","malocclusion"],"defaultValues":{"toothCount":4,"cariesCount":0,"gumCondition":"正常","oralHygiene":"良好"}}',
   '{"toothCount":"number","cariesCount":"number","dmftIndex":"number"}',
   '{"abnormalThreshold":{"cariesCount":">0","oralHygiene":"差"}}',
   '{"guidance":"乳牙萌出期，注意喂养姿势，避免奶瓶龋"}',
   '{"recommendation":"下次口腔保健检查时间：12月龄","followupType":"ORAL_HEALTH"}',
   4, 1),
  ('ORAL-12M', '12月龄口腔保健病历模板', 'ORAL_HEALTH', 11, 14,
   '《儿童口腔保健指导技术规范》', '婴儿12月龄口腔保健检查标准模板',
   '{"schemaVersion":1,"items":["toothCount","cariesCount","missingTooth","filledTooth","dmftIndex","cariesType","gumCondition","oralMucosa","tongue","palate","occlusion","oralHygiene","malocclusion"],"defaultValues":{"toothCount":8,"cariesCount":0,"dmftIndex":0,"gumCondition":"正常","oralHygiene":"良好"}}',
   '{"toothCount":"number","cariesCount":"number","dmftIndex":"number"}',
   '{"abnormalThreshold":{"cariesCount":">0","dmftIndex":">0","gumCondition":"异常"}}',
   '{"guidance":"断奶瓶，开始使用婴幼儿牙刷，每半年口腔检查"}',
   '{"recommendation":"下次口腔保健检查时间：18月龄","followupType":"ORAL_HEALTH"}',
   5, 1),
  ('ORAL-18M', '18月龄口腔保健病历模板', 'ORAL_HEALTH', 15, 20,
   '《儿童口腔保健指导技术规范》', '幼儿18月龄口腔保健检查标准模板',
   '{"schemaVersion":1,"items":["toothCount","cariesCount","missingTooth","filledTooth","dmftIndex","cariesType","gumCondition","oralMucosa","tongue","palate","occlusion","oralHygiene","malocclusion"],"defaultValues":{"toothCount":12,"cariesCount":0,"dmftIndex":0,"gumCondition":"正常","oralHygiene":"良好","malocclusion":"无"}}',
   '{"toothCount":"number","cariesCount":"number","dmftIndex":"number","malocclusion":"无|有"}',
   '{"abnormalThreshold":{"cariesCount":">0","dmftIndex":">0","malocclusion":"有"}}',
   '{"guidance":"乳磨牙萌出，可使用含氟牙膏（米粒大小）"}',
   '{"recommendation":"下次口腔保健检查时间：24月龄","followupType":"ORAL_HEALTH"}',
   6, 1),
  ('ORAL-24M', '24月龄口腔保健病历模板', 'ORAL_HEALTH', 21, 26,
   '《儿童口腔保健指导技术规范》', '幼儿24月龄口腔保健检查标准模板',
   '{"schemaVersion":1,"items":["toothCount","cariesCount","missingTooth","filledTooth","dmftIndex","cariesType","gumCondition","oralMucosa","tongue","palate","occlusion","oralHygiene","malocclusion"],"defaultValues":{"toothCount":16,"cariesCount":0,"dmftIndex":0,"gumCondition":"正常","oralHygiene":"良好","malocclusion":"无"}}',
   '{"toothCount":"number","cariesCount":"number","dmftIndex":"number","malocclusion":"无|有"}',
   '{"abnormalThreshold":{"cariesCount":">0","dmftIndex":">0","malocclusion":"有","occlusion":"异常"}}',
   '{"guidance":"20 颗乳牙基本萌齐，开始培养刷牙习惯，家长协助"}',
   '{"recommendation":"下次口腔保健检查时间：30月龄","followupType":"ORAL_HEALTH"}',
   7, 1),
  ('ORAL-30M', '30月龄口腔保健病历模板', 'ORAL_HEALTH', 27, 35,
   '《儿童口腔保健指导技术规范》', '幼儿30月龄口腔保健检查标准模板',
   '{"schemaVersion":1,"items":["toothCount","cariesCount","missingTooth","filledTooth","dmftIndex","cariesType","gumCondition","oralMucosa","tongue","palate","occlusion","oralHygiene","malocclusion"],"defaultValues":{"toothCount":20,"cariesCount":0,"dmftIndex":0,"gumCondition":"正常","oralHygiene":"良好","malocclusion":"无"}}',
   '{"toothCount":"number","cariesCount":"number","dmftIndex":"number","malocclusion":"无|有"}',
   '{"abnormalThreshold":{"cariesCount":">0","dmftIndex":">0","malocclusion":"有"}}',
   '{"guidance":"20 颗乳牙萌齐，每半年口腔检查，必要时局部涂氟"}',
   '{"recommendation":"下次口腔保健检查时间：3岁","followupType":"ORAL_HEALTH"}',
   8, 1),
  ('ORAL-3Y', '3岁口腔保健病历模板', 'ORAL_HEALTH', 36, 42,
   '《儿童口腔保健指导技术规范》', '学龄前儿童3岁口腔保健检查标准模板',
   '{"schemaVersion":1,"items":["toothCount","cariesCount","missingTooth","filledTooth","dmftIndex","cariesType","gumCondition","oralMucosa","tongue","palate","occlusion","oralHygiene","malocclusion"],"defaultValues":{"toothCount":20,"cariesCount":0,"dmftIndex":0,"gumCondition":"正常","oralHygiene":"良好","malocclusion":"无"}}',
   '{"toothCount":"number","cariesCount":"number","dmftIndex":"number","malocclusion":"无|有"}',
   '{"abnormalThreshold":{"cariesCount":">0","dmftIndex":">0","malocclusion":"有","occlusion":"异常"}}',
   '{"guidance":"入园前完成龋齿筛查，建立口腔健康档案"}',
   '{"recommendation":"每半年 1 次口腔检查","followupType":"ORAL_HEALTH"}',
   9, 1),
  ('ORAL-4Y', '4岁口腔保健病历模板', 'ORAL_HEALTH', 43, 54,
   '《儿童口腔保健指导技术规范》', '学龄前儿童4岁口腔保健检查标准模板',
   '{"schemaVersion":1,"items":["toothCount","cariesCount","missingTooth","filledTooth","dmftIndex","cariesType","gumCondition","oralMucosa","tongue","palate","occlusion","oralHygiene","malocclusion"],"defaultValues":{"toothCount":20,"cariesCount":0,"dmftIndex":0,"gumCondition":"正常","oralHygiene":"良好","malocclusion":"无"}}',
   '{"toothCount":"number","cariesCount":"number","dmftIndex":"number","malocclusion":"无|有"}',
   '{"abnormalThreshold":{"cariesCount":">0","dmftIndex":">0","malocclusion":"有"}}',
   '{"guidance":"家长协助刷牙，使用含氟牙膏（豌豆大小）"}',
   '{"recommendation":"每半年 1 次口腔检查","followupType":"ORAL_HEALTH"}',
   10, 1),
  ('ORAL-5Y', '5岁口腔保健病历模板', 'ORAL_HEALTH', 55, 66,
   '《儿童口腔保健指导技术规范》', '学龄前儿童5岁口腔保健检查标准模板',
   '{"schemaVersion":1,"items":["toothCount","cariesCount","missingTooth","filledTooth","dmftIndex","cariesType","gumCondition","oralMucosa","tongue","palate","occlusion","oralHygiene","malocclusion"],"defaultValues":{"toothCount":20,"cariesCount":0,"dmftIndex":0,"gumCondition":"正常","oralHygiene":"良好","malocclusion":"无"}}',
   '{"toothCount":"number","cariesCount":"number","dmftIndex":"number","malocclusion":"无|有"}',
   '{"abnormalThreshold":{"cariesCount":">0","dmftIndex":">0","malocclusion":"有","occlusion":"异常"}}',
   '{"guidance":"学龄前完成龋齿治疗，关注恒牙萌出"}',
   '{"recommendation":"每半年 1 次口腔检查","followupType":"ORAL_HEALTH"}',
   11, 1),
  ('ORAL-6Y', '6岁口腔保健病历模板', 'ORAL_HEALTH', 67, 78,
   '《儿童口腔保健指导技术规范》', '学龄儿童6岁口腔保健检查标准模板',
   '{"schemaVersion":1,"items":["toothCount","cariesCount","missingTooth","filledTooth","dmftIndex","cariesType","gumCondition","oralMucosa","tongue","palate","occlusion","oralHygiene","malocclusion"],"defaultValues":{"toothCount":24,"cariesCount":0,"dmftIndex":0,"gumCondition":"正常","oralHygiene":"良好","malocclusion":"无"}}',
   '{"toothCount":"number","cariesCount":"number","dmftIndex":"number","malocclusion":"无|有"}',
   '{"abnormalThreshold":{"cariesCount":">0","dmftIndex":">0","malocclusion":"有","occlusion":"异常"}}',
   '{"guidance":"第一恒磨牙萌出，及时窝沟封闭，建立长期口腔健康档案"}',
   '{"recommendation":"建议每年至少 1 次口腔检查","followupType":"ORAL_HEALTH"}',
   12, 1);

-- 4. 体格检查病历模板（需求13，12 套）—— 一并补齐 P2 阶段数据
INSERT IGNORE INTO `medical_record_template`
  (`template_code`, `template_name`, `template_type`, `age_month_min`, `age_month_max`,
   `norm_version`, `description`, `template_content`, `field_mapping`,
   `abnormality_thresholds`, `health_guidance`, `follow_up_recommendation`,
   `sort_order`, `status`)
VALUES
  ('PHYSICAL-01M', '满月体格检查病历模板', 'GENERAL_CHECKUP', 0, 1,
   '《国家基本公共卫生服务规范（第三版）》', '新生儿满月健康检查标准模板',
   '{"schemaVersion":1,"items":["height","weight","headCircumference","chestCircumference","bmi","bodyTemp","heartRate","respiratoryRate","skinCondition","lymphNode","headShape","fontanelle","chestExam","heartExam","lungExam","abdomenExam","spineExam","limbsExam","genitalia","nervousSystem","growthAssessment"],"defaultValues":{"fontanelle":"未闭","growthAssessment":"正常"}}',
   '{"height":"number","weight":"number","headCircumference":"number","chestCircumference":"number"}',
   '{"abnormalThreshold":{"weight":"<2.5|>4.0","height":"<46|>56","bodyTemp":">37.5","heartRate":">160|<100","respiratoryRate":">60|<30"}}',
   '{"guidance":"母乳喂养、维生素 D 补充、注意黄疸消退"}',
   '{"recommendation":"下次体检时间：3月龄","followupType":"ROUTINE"}',
   1, 1),
  ('PHYSICAL-03M', '3月龄体格检查病历模板', 'GENERAL_CHECKUP', 2, 4,
   '《国家基本公共卫生服务规范（第三版）》', '婴儿3月龄健康检查标准模板',
   '{"schemaVersion":1,"items":["height","weight","headCircumference","chestCircumference","bmi","bodyTemp","heartRate","respiratoryRate","skinCondition","lymphNode","headShape","fontanelle","chestExam","heartExam","lungExam","abdomenExam","spineExam","limbsExam","genitalia","nervousSystem","growthAssessment"],"defaultValues":{"fontanelle":"未闭","growthAssessment":"正常"}}',
   '{"height":"number","weight":"number","headCircumference":"number"}',
   '{"abnormalThreshold":{"weight":"<3.3|>6.5","height":"<55|>65"}}',
   '{"guidance":"母乳/配方奶喂养，培养规律作息，多趴着练习抬头"}',
   '{"recommendation":"下次体检时间：6月龄","followupType":"ROUTINE"}',
   2, 1),
  ('PHYSICAL-06M', '6月龄体格检查病历模板', 'GENERAL_CHECKUP', 5, 7,
   '《国家基本公共卫生服务规范（第三版）》', '婴儿6月龄健康检查标准模板',
   '{"schemaVersion":1,"items":["height","weight","headCircumference","chestCircumference","bmi","bodyTemp","heartRate","respiratoryRate","skinCondition","lymphNode","headShape","fontanelle","chestExam","heartExam","lungExam","abdomenExam","spineExam","limbsExam","genitalia","nervousSystem","growthAssessment"],"defaultValues":{"fontanelle":"未闭","growthAssessment":"正常"}}',
   '{"height":"number","weight":"number","headCircumference":"number"}',
   '{"abnormalThreshold":{"weight":"<5.5|>9.0","height":"<63|>73"}}',
   '{"guidance":"开始添加辅食，铁强化食品优先；练习翻身、独坐"}',
   '{"recommendation":"下次体检时间：8月龄","followupType":"ROUTINE"}',
   3, 1),
  ('PHYSICAL-08M', '8月龄体格检查病历模板', 'GENERAL_CHECKUP', 8, 10,
   '《国家基本公共卫生服务规范（第三版）》', '婴儿8月龄健康检查标准模板',
   '{"schemaVersion":1,"items":["height","weight","headCircumference","chestCircumference","bmi","bodyTemp","heartRate","respiratoryRate","skinCondition","lymphNode","headShape","fontanelle","chestExam","heartExam","lungExam","abdomenExam","spineExam","limbsExam","genitalia","nervousSystem","growthAssessment"],"defaultValues":{"fontanelle":"未闭","growthAssessment":"正常"}}',
   '{"height":"number","weight":"number","headCircumference":"number"}',
   '{"abnormalThreshold":{"weight":"<6.5|>10.0","height":"<66|>77"}}',
   '{"guidance":"丰富辅食种类，练习爬行，关注语言发育"}',
   '{"recommendation":"下次体检时间：12月龄","followupType":"ROUTINE"}',
   4, 1),
  ('PHYSICAL-12M', '12月龄体格检查病历模板', 'GENERAL_CHECKUP', 11, 14,
   '《国家基本公共卫生服务规范（第三版）》', '婴儿12月龄健康检查标准模板',
   '{"schemaVersion":1,"items":["height","weight","headCircumference","chestCircumference","bmi","bodyTemp","heartRate","respiratoryRate","skinCondition","lymphNode","headShape","fontanelle","chestExam","heartExam","lungExam","abdomenExam","spineExam","limbsExam","genitalia","nervousSystem","growthAssessment"],"defaultValues":{"fontanelle":"未闭","growthAssessment":"正常"}}',
   '{"height":"number","weight":"number","headCircumference":"number"}',
   '{"abnormalThreshold":{"weight":"<7.5|>11.5","height":"<71|>82"}}',
   '{"guidance":"断奶瓶，过渡到家庭饮食；学步期注意安全"}',
   '{"recommendation":"下次体检时间：18月龄","followupType":"ROUTINE"}',
   5, 1),
  ('PHYSICAL-18M', '18月龄体格检查病历模板', 'GENERAL_CHECKUP', 15, 20,
   '《国家基本公共卫生服务规范（第三版）》', '幼儿18月龄健康检查标准模板',
   '{"schemaVersion":1,"items":["height","weight","headCircumference","chestCircumference","bmi","bodyTemp","heartRate","respiratoryRate","skinCondition","lymphNode","headShape","fontanelle","chestExam","heartExam","lungExam","abdomenExam","spineExam","limbsExam","genitalia","nervousSystem","growthAssessment"],"defaultValues":{"fontanelle":"已闭","growthAssessment":"正常"}}',
   '{"height":"number","weight":"number","headCircumference":"number"}',
   '{"abnormalThreshold":{"weight":"<9.0|>13.0","height":"<76|>88"}}',
   '{"guidance":"培养自主进食，语言表达训练，社交能力培养"}',
   '{"recommendation":"下次体检时间：24月龄","followupType":"ROUTINE"}',
   6, 1),
  ('PHYSICAL-24M', '24月龄体格检查病历模板', 'GENERAL_CHECKUP', 21, 26,
   '《国家基本公共卫生服务规范（第三版）》', '幼儿24月龄健康检查标准模板',
   '{"schemaVersion":1,"items":["height","weight","headCircumference","chestCircumference","bmi","bodyTemp","heartRate","respiratoryRate","skinCondition","lymphNode","headShape","fontanelle","chestExam","heartExam","lungExam","abdomenExam","spineExam","limbsExam","genitalia","nervousSystem","growthAssessment"],"defaultValues":{"fontanelle":"已闭","growthAssessment":"正常"}}',
   '{"height":"number","weight":"number","headCircumference":"number"}',
   '{"abnormalThreshold":{"weight":"<10.0|>14.5","height":"<80|>93"}}',
   '{"guidance":"控制糖摄入，培养刷牙习惯；如厕训练；规则意识建立"}',
   '{"recommendation":"下次体检时间：30月龄","followupType":"ROUTINE"}',
   7, 1),
  ('PHYSICAL-30M', '30月龄体格检查病历模板', 'GENERAL_CHECKUP', 27, 35,
   '《国家基本公共卫生服务规范（第三版）》', '幼儿30月龄健康检查标准模板',
   '{"schemaVersion":1,"items":["height","weight","headCircumference","chestCircumference","bmi","bodyTemp","heartRate","respiratoryRate","skinCondition","lymphNode","headShape","fontanelle","chestExam","heartExam","lungExam","abdomenExam","spineExam","limbsExam","genitalia","nervousSystem","growthAssessment"],"defaultValues":{"fontanelle":"已闭","growthAssessment":"正常"}}',
   '{"height":"number","weight":"number","headCircumference":"number"}',
   '{"abnormalThreshold":{"weight":"<11.0|>16.0","height":"<85|>98"}}',
   '{"guidance":"均衡饮食，规律作息；培养运动协调能力"}',
   '{"recommendation":"下次体检时间：3岁","followupType":"ROUTINE"}',
   8, 1),
  ('PHYSICAL-3Y', '3岁体格检查病历模板', 'GENERAL_CHECKUP', 36, 42,
   '《国家基本公共卫生服务规范（第三版）》', '学龄前儿童3岁健康检查标准模板',
   '{"schemaVersion":1,"items":["height","weight","headCircumference","chestCircumference","bmi","bodyTemp","heartRate","respiratoryRate","skinCondition","lymphNode","headShape","fontanelle","chestExam","heartExam","lungExam","abdomenExam","spineExam","limbsExam","genitalia","nervousSystem","growthAssessment"],"defaultValues":{"fontanelle":"已闭","growthAssessment":"正常"}}',
   '{"height":"number","weight":"number","headCircumference":"number"}',
   '{"abnormalThreshold":{"weight":"<12.0|>17.5","height":"<89|>103"}}',
   '{"guidance":"入园前体检，建立视力、听力、口腔档案；预防意外伤害"}',
   '{"recommendation":"每年 1 次健康检查","followupType":"ROUTINE"}',
   9, 1),
  ('PHYSICAL-4Y', '4岁体格检查病历模板', 'GENERAL_CHECKUP', 43, 54,
   '《国家基本公共卫生服务规范（第三版）》', '学龄前儿童4岁健康检查标准模板',
   '{"schemaVersion":1,"items":["height","weight","headCircumference","chestCircumference","bmi","bodyTemp","heartRate","respiratoryRate","skinCondition","lymphNode","headShape","fontanelle","chestExam","heartExam","lungExam","abdomenExam","spineExam","limbsExam","genitalia","nervousSystem","growthAssessment"],"defaultValues":{"fontanelle":"已闭","growthAssessment":"正常"}}',
   '{"height":"number","weight":"number","headCircumference":"number"}',
   '{"abnormalThreshold":{"weight":"<13.5|>20.0","height":"<94|>110"}}',
   '{"guidance":"每日户外活动 ≥2 小时，预防近视；关注语言表达及社交发育"}',
   '{"recommendation":"每年 1 次健康检查","followupType":"ROUTINE"}',
   10, 1),
  ('PHYSICAL-5Y', '5岁体格检查病历模板', 'GENERAL_CHECKUP', 55, 66,
   '《国家基本公共卫生服务规范（第三版）》', '学龄前儿童5岁健康检查标准模板',
   '{"schemaVersion":1,"items":["height","weight","headCircumference","chestCircumference","bmi","bodyTemp","heartRate","respiratoryRate","skinCondition","lymphNode","headShape","fontanelle","chestExam","heartExam","lungExam","abdomenExam","spineExam","limbsExam","genitalia","nervousSystem","growthAssessment"],"defaultValues":{"fontanelle":"已闭","growthAssessment":"正常"}}',
   '{"height":"number","weight":"number","headCircumference":"number"}',
   '{"abnormalThreshold":{"weight":"<15.0|>22.0","height":"<99|>117"}}',
   '{"guidance":"入学前准备，加强运动协调能力培养，关注视力变化"}',
   '{"recommendation":"每年 1 次健康检查","followupType":"ROUTINE"}',
   11, 1),
  ('PHYSICAL-6Y', '6岁体格检查病历模板', 'GENERAL_CHECKUP', 67, 78,
   '《国家基本公共卫生服务规范（第三版）》', '学龄儿童6岁健康检查标准模板',
   '{"schemaVersion":1,"items":["height","weight","headCircumference","chestCircumference","bmi","bodyTemp","heartRate","respiratoryRate","skinCondition","lymphNode","headShape","fontanelle","chestExam","heartExam","lungExam","abdomenExam","spineExam","limbsExam","genitalia","nervousSystem","growthAssessment"],"defaultValues":{"fontanelle":"已闭","growthAssessment":"正常"}}',
   '{"height":"number","weight":"number","headCircumference":"number"}',
   '{"abnormalThreshold":{"weight":"<16.0|>24.0","height":"<104|>124"}}',
   '{"guidance":"入学前完成全面体检，建立长期健康档案；加强安全教育"}',
   '{"recommendation":"建议每年 1 次健康检查","followupType":"ROUTINE"}',
   12, 1);

-- 5. 同步初始化 6 类专案类型配置（CaseTypeConfig，供 P1-3 异常自动建专案使用）
INSERT IGNORE INTO `childhealth_case_type_config`
  (`type_code`, `type_name`, `category`, `follow_frequency`, `case_card_template`,
   `follow_template`, `discharge_criteria`, `status`)
VALUES
  ('HIGH_RISK_NEWBORN', '高危新生儿专案', '高危',
   '每月随访至 6 月龄，之后每 3 月随访至 2 岁',
   '{"sections":["基本信息","初始评估","风险因素","干预方案","随访计划","康复评估"]}',
   '{"sections":["随访日期","随访方式","体格测量","神经心理评估","喂养指导","下次计划"]}',
   '风险因素解除且连续 2 次评估达标', 1),
  ('GROWTH_MANAGEMENT', '生长发育管理专案', '生长发育',
   '每 1-3 月随访至指标稳定',
   '{"sections":["基本信息","生长指标","SD/百分位","病因分析","干预方案","随访计划"]}',
   '{"sections":["随访日期","身高","体重","BMI","SD值","干预效果","下次计划"]}',
   '生长指标恢复至正常范围并稳定 6 月', 1),
  ('EYE_HEALTH', '眼保健专案', '五官',
   '每 1-3 月随访至指标稳定',
   '{"sections":["基本信息","眼科诊断","屈光检查","干预方案","随访计划"]}',
   '{"sections":["随访日期","视力","屈光度","眼位","干预效果","下次计划"]}',
   '视力、屈光度恢复至正常范围并稳定 6 月', 1),
  ('HEARING_HEALTH', '听力保健专案', '五官',
   '每 1-3 月随访至指标稳定',
   '{"sections":["基本信息","听力诊断","听力学检查","干预方案","随访计划"]}',
   '{"sections":["随访日期","左耳听力","右耳听力","AABR结果","干预效果","下次计划"]}',
   '听力筛查连续 2 次通过或听力稳定', 1),
  ('ORAL_HEALTH', '口腔保健专案', '五官',
   '每 3-6 月随访至龋齿治疗完成',
   '{"sections":["基本信息","口腔诊断","dmft记录","干预方案","随访计划"]}',
   '{"sections":["随访日期","牙齿数量","龋齿数","补牙数","口腔卫生","下次计划"]}',
   '龋齿治疗完成且新发龋齿率下降', 1),
  ('SPECIALTY_FOLLOW_UP', '其他专案随访', '综合',
   '按医嘱随访',
   '{"sections":["基本信息","诊断","干预方案","随访计划"]}',
   '{"sections":["随访日期","健康状况","干预效果","下次计划"]}',
   '原发疾病稳定或治愈', 1),
  ('MALNUTRITION', '营养不良专案', '营养',
   '每月随访至指标稳定 6 月',
   '{"sections":["基本信息","营养评估","膳食调查","病因分析","干预方案","随访计划"]}',
   '{"sections":["随访日期","身高","体重","SD/百分位","膳食指导","下次计划"]}',
   '体重/身高恢复至正常范围并稳定 6 月', 1),
  ('OBESITY', '肥胖儿专案', '营养',
   '每月随访至 BMI 下降至正常范围',
   '{"sections":["基本信息","BMI评估","膳食调查","运动方案","随访计划"]}',
   '{"sections":["随访日期","身高","体重","BMI","运动情况","膳食指导","下次计划"]}',
   'BMI 下降至正常范围并稳定 6 月', 1),
  ('ANEMIA', '贫血儿专案', '疾病',
   '每月随访至血红蛋白达标 3 月',
   '{"sections":["基本信息","贫血诊断","血红蛋白","铁代谢","干预方案","随访计划"]}',
   '{"sections":["随访日期","血红蛋白","血清铁","膳食指导","干预效果","下次计划"]}',
   '血红蛋白连续 3 次达标', 1),
  ('RICKETS', '佝偻病儿专案', '疾病',
   '每月随访至临床缓解 3 月',
   '{"sections":["基本信息","佝偻病诊断","维生素D","骨密度","干预方案","随访计划"]}',
   '{"sections":["随访日期","体征","维生素D","骨密度","干预效果","下次计划"]}',
   '临床体征缓解且维生素 D 恢复正常', 1),
  ('DEVELOPMENTAL_DISORDER', '发育行为异常专案', '发育行为',
   '按评估结果制定',
   '{"sections":["基本信息","发育评估","量表结果","干预方案","随访计划"]}',
   '{"sections":["随访日期","量表评估","行为表现","干预效果","下次计划"]}',
   '复评达到正常范围并稳定 6 月', 1);

COMMIT;

-- 校验
SELECT
  template_type,
  COUNT(*) AS template_count
FROM `medical_record_template`
WHERE `status` = 1
GROUP BY `template_type`
ORDER BY `template_type`;

SELECT
  type_code,
  type_name
FROM `childhealth_case_type_config`
WHERE `status` = 1
ORDER BY `category`, `type_code`;
