package cn.iocoder.yudao.module.childhealth.controller.admin.ops;
import cn.iocoder.yudao.framework.common.pojo.CommonResult; import cn.iocoder.yudao.module.childhealth.api.ops.dto.ChildHealthOpsDTO.*; import cn.iocoder.yudao.module.childhealth.service.ops.ChildHealthOpsService; import jakarta.annotation.Resource; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.List; import static cn.iocoder.yudao.framework.common.pojo.CommonResult.success;
@RestController @RequestMapping("/childhealth/ops") public class ChildHealthOpsController {
 @Resource private ChildHealthOpsService service;
 @PostMapping("/message/push") @PreAuthorize("@ss.hasPermission('childhealth:ops:message')") public CommonResult<Long> message(@Valid @RequestBody MessagePushRequest request){return success(service.queueMessage(request));}
 @GetMapping("/message") @PreAuthorize("@ss.hasPermission('childhealth:ops:message')") public CommonResult<List<MessagePushResponse>> messages(@RequestParam(required=false) Long targetId,@RequestParam(required=false) Integer status){return success(service.listMessages(targetId,status));}
 @PostMapping("/message/{id}/resend") @PreAuthorize("@ss.hasPermission('childhealth:ops:message')") public CommonResult<Boolean> resend(@PathVariable Long id){service.resendMessage(id);return success(true);}
 @PostMapping("/message/{id}/cancel") @PreAuthorize("@ss.hasPermission('childhealth:ops:message')") public CommonResult<Boolean> cancel(@PathVariable Long id){service.cancelMessage(id);return success(true);}
 @PutMapping("/message/{id}/read") @PreAuthorize("@ss.hasPermission('childhealth:ops:message')") public CommonResult<Boolean> read(@PathVariable Long id){service.markMessageRead(id);return success(true);}
 @PostMapping("/reminder") @PreAuthorize("@ss.hasPermission('childhealth:ops:reminder')") public CommonResult<Long> reminder(@Valid @RequestBody ReminderRequest request){return success(service.createReminder(request));}
 @PostMapping("/reminder/generate") @PreAuthorize("@ss.hasPermission('childhealth:ops:reminder')") public CommonResult<Integer> generate(@RequestBody ReminderGenerateRequest request){return success(service.generateReminders(request));}
 @PostMapping("/questionnaire") @PreAuthorize("@ss.hasPermission('childhealth:ops:questionnaire')") public CommonResult<Long> questionnaire(@Valid @RequestBody QuestionnaireRequest request){return success(service.createQuestionnaire(request));}
 @PostMapping("/questionnaire/answer") @PreAuthorize("@ss.hasPermission('childhealth:ops:questionnaire')") public CommonResult<Long> answer(@Valid @RequestBody QuestionnaireAnswerRequest request){return success(service.submitQuestionnaireAnswer(request));}
 @GetMapping("/questionnaire/answer") @PreAuthorize("@ss.hasPermission('childhealth:ops:questionnaire')") public CommonResult<List<QuestionnaireAnswerResponse>> answers(@RequestParam(required=false) Long childId,@RequestParam(required=false) Long questionnaireId){return success(service.listQuestionnaireAnswers(childId,questionnaireId));}
 @PostMapping("/article") @PreAuthorize("@ss.hasPermission('childhealth:ops:article')") public CommonResult<Long> article(@Valid @RequestBody ArticleRequest request){return success(service.createArticle(request));}
 @GetMapping("/article/list") @PreAuthorize("@ss.hasPermission('childhealth:ops:article')") public CommonResult<List<ArticleResponse>> articles(@RequestParam(required=false) Integer status){return success(service.listArticles(status));}
}
