package cn.iocoder.yudao.module.childhealth.dal.dataobject.medical;

import cn.iocoder.yudao.framework.mybatis.core.dataobject.BaseDO;
import com.baomidou.mybatisplus.annotation.KeySequence;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * 病历主表 DO
 *
 * 对应表: medical_record
 * 模块: A. 儿童基础健康检查（A2-病历主表）
 * 创建日期: 2026-07-20
 */
@TableName("medical_record")
@KeySequence("medical_record_seq")
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MedicalRecordDO extends BaseDO {

    /**
     * 主键ID
     */
    @TableId
    private Long id;

    /**
     * 病历号
     */
    private String recordNo;

    /**
     * 儿童档案ID
     */
    private Long childId;

    /**
     * 学生ID
     */
    private Long studentId;

    /**
     * 病历模板ID
     */
    private Long templateId;

    /**
     * 体检记录ID（用于关联体检记录，workflow 流程使用）
     */
    private Long examId;

    /**
     * 筛查批次ID
     */
    private Long batchId;

    /**
     * 就诊日期
     */
    private LocalDate visitDate;

    /**
     * 就诊类型 1满月 2常规体检 3入园入托 4转诊 5复诊
     */
    private Integer visitType;

    /**
     * 月龄
     */
    private Integer ageMonth;

    /**
     * 主诉
     */
    private String chiefComplaint;

    /**
     * 现病史
     */
    private String presentIllness;

    /**
     * 既往史
     */
    private String pastHistory;

    /**
     * 体格检查
     */
    private String physicalExam;

    /**
     * 专科检查
     */
    private String specialistExam;

    /**
     * 辅助检查
     */
    private String auxExam;

    /**
     * 诊断
     */
    private String diagnosis;

    /**
     * 健康指导
     */
    private String healthGuidance;

    /**
     * 下次就诊建议
     */
    private String nextVisitAdvice;

    /**
     * 医生ID
     */
    private Long doctorId;

    /**
     * 医生姓名
     */
    private String doctorName;

    /**
     * 科室ID
     */
    private Long deptId;

    /**
     * 是否自动生成（workflow 自动组装病历时标记）
     */
    private Boolean isAutoGenerated;

    /**
     * 病历记录时间（workflow 自动组装时写入）
     */
    private LocalDateTime recordTime;

    /**
     * 专案提醒状态 0未提醒 1已提醒建专案
     */
    private Integer caseRemindStatus;

    /**
     * 审核状态 0未审核 1已审核 2已驳回
     */
    private Integer auditStatus;

    /**
     * 审核医生ID
     */
    private Long auditDoctorId;

    /**
     * 审核时间
     */
    private LocalDateTime auditTime;

}
